filebeat.inputs:
  - type: filestream
    id: ledger-strangler-platform-services
    paths:
      - "/var/log/ledger-strangler-platform/*.log"
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
